name: 02 - Workflow de Teste (CI)

on: [push, pull_request]

jobs:
    
  dizer_ola:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Baixar o Código
        run: actions/checkout@v4

      - name: 2. Configurar ambiente (ex. Node.js)
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 3. Instalar dependências
        run: echo 'simulando npm install'

      - name: 4. Executar testes
        run: echo 'simulando npm test'
